title: Risk-data Library
author:
  name: Global Facility for Disaster Reduction and Recovery
markdown: kramdown

sass:
  # sass_dir: _sass -- default
  style: compressed

collections:
  components:
    permalink: /:collection/:name
    sort_by: order
    output: true
  documentation:
    permalink: /:collection/:name
    sort_by: order
    output: true

google_analytics: 'UA-164674068-1'
