version: '3.7'

services:
  app:
    container_name: site
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 4000:4000
    command: >
      bundle exec jekyll serve --watch --host=0.0.0.0 --incremental
